### ISSUE TITLE
Let People Self-Add to Slack

### ISSUE THREAD

**Issue by U8NWXD** [codethechange/codethechange.github.io#41]
Just like we let people add themselves to our mailing list, should they be able to add themselves to our Slack?

**Comment by DrewGregory** [comment]
This could be interesting, but I would be concerned about non-Stanford-students adding themselves and spamming the workspace. Do you know of ways to limit/mitigate this?

**Comment by U8NWXD** [comment]
Ahh, good point. I don't know of a way right now, so let's put this on hold for now.
